run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/SnakebiteEF2000/kubecnf
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen

  exclude-use-default: false
  exclude:
    # Exclude some common false positives
    - "G404: Use of weak random number generator"
    - "G306: Expect WriteFile permissions to be 0600 or less"

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false 