name: Build Go Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Go binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/kubecnf_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: kubecnf-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bin/kubecnf_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Trigger release workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"create-release"}'

